# Example 30
apiVersion: v1
kind: Service
metadata:
  name: kuard-rs-test-nodeport-service
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 32080 # Listening port on External IPs
    port: 8090 # Listening port on Internal IPs
    targetPort: 8080 # Pod’s listening port
    protocol: TCP
  selector:
    app: kuard-rs-test-pod

